version: "3"
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: cluster1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.0.2:9092,192.168.0.2:19092,192.168.0.2:29092
    networks:
      - kafka-net
networks:
  kafka-net:
    external: true