version: "3"
services:
  kafka-broker:
    container_name: kafka-broker
    image: 'bitnami/kafka:latest'
    volumes:
      - kafka01-data:/bitnami/kafka
    ports:
      - '9092'
      - '9093'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_KRAFT_CLUSTER_ID: 10HT3ErKTyKq9iXHk0EfBg
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker:9093
    networks:
      - kafka-net
volumes:
  kafka-broker-data:
    driver: local