---
version: '3'
services:
  zookeeper01:
    container_name: zookeeper01
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - kafka-net
  zookeeper02:
    container_name: zookeeper02
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - kafka-net
  zookeeper03:
    container_name: zookeeper03
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - kafka-net
networks:
  kafka-net:
    external: true